name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: |
        docker build -t docker-registry.local/kdjdk:${{ github.sha }} .
        docker tag docker-registry.local/kdjdk:${{ github.sha }} docker-registry.local/kdjdk:latest

    - name: Push to local registry
      run: |
        docker push docker-registry.local/kdjdk:${{ github.sha }}
        docker push docker-registry.local/kdjdk:latest
